# Generated by Django 3.2.5 on 2021-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0002_auto_20210725_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='auto_class',
            field=models.CharField(choices=[('e', 'economy'), ('c', 'comfort'), ('b', 'business')], default='e', max_length=1, null=True, verbose_name='Класс авто'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год'),
        ),
    ]
