# Generated by Django 3.2.5 on 2021-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0004_auto_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jgwbb',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='options',
            field=models.ManyToManyField(to='motorpool.Option'),
        ),
    ]
