# Generated by Django 3.2.5 on 2021-07-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0006_auto_20210725_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='vehiclepassport',
            options={'verbose_name_plural': 'Паспорта машин'},
        ),
    ]
