# Generated by Django 3.2.5 on 2021-08-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0008_auto_20210728_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='motorpool/brands/'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='motorpool.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='options',
            field=models.ManyToManyField(related_name='cars', to='motorpool.Option', verbose_name='Опции'),
        ),
    ]
